### ISSUE TITLE
Getting there was a problem in bringing the project 

### ISSUE THREAD

**Issue by chaitanyashastry1** [DannyDainton/basic-newman-slack-bot#6]
I am getting port 3000 is already in use

Kindly help me Danny

**Comment by DannyDainton** [comment]
Hey @chaitanyashastry1,

Really sorry, I only just saw this :( I haven't looked at the repo for a while. 

Are you using something else on port 3000 - You could just change all the places in the code to point to a different port? I only added 3000 because that's what I was using in local dev but you could have any open port to be honest.
